export default {
  play: require("../assets/Icons/play.png"),
  bookmark: require("../assets/Icons/bookmark.png"),
  home: require("../assets/Icons/home.png"),
  plus: require("../assets/Icons/plus.png"),
  profile: require("../assets/Icons/profile.png"),
  leftArrow: require("../assets/Icons/left-arrow.png"),
  menu: require("../assets/Icons/menu.png"),
  search: require("../assets/Icons/search.png"),
  upload: require("../assets/Icons/upload.png"),
  rightArrow: require("../assets/Icons/right-arrow.png"),
  logout: require("../assets/Icons/logout.png"),
  eyeHide: require("../assets/Icons/eye-hide.png"),
  eye: require("../assets/Icons/eye.png"),
};
